version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-backend
    restart: always
    working_dir: /app/backend
    volumes:
      - ./backend:/app/backend
      - /app/backend/node_modules
    ports:
      - "5000:5000"
    command: bash -c "npm init -y && npm install && npm update && npm start"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/mernapp
  mongo:
    image: mongo:5.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
