#!/bin/bash

# Stop and remove containers
docker-compose down

# Rebuild, and run the containers
docker-compose up --build -d


# Test update
# Test update 2
# Test update 3
# Test update 4
# Test update 5
# Test update 6
# Test update 7
# Test update 8
# Test update 9
# Test update 10
